#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

#include "msys_sonic_device.h"

int sonic_process_api(clixon_handle h, void *req, cvec *qvec, const char *device_url, const char *ip_address, const char *request_method){
    CURL *curl;
    CURLcode res;
    char url[512];

    if (!device_url || !ip_address || !request_method) {
        printf("Error: Missing required parameters.\n");
        return -1;
    }

    /* Construct the full API URL */
    snprintf(url, sizeof(url), "http://%s%s", ip_address, device_url);

    /* Initialize CURL */
    curl = curl_easy_init();
    if (!curl) {
        printf("Error: Failed to initialize CURL.\n");
        return -1;
    }

    /* Set the URL */
    curl_easy_setopt(curl, CURLOPT_URL, url);

    /* Set request method */
    if (strcmp(request_method, "POST") == 0) {
        curl_easy_setopt(curl, CURLOPT_POST, 1L);
    } else if (strcmp(request_method, "PUT") == 0) {
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "PUT");
    } else if (strcmp(request_method, "DELETE") == 0) {
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "DELETE");
    } // Default is GET, so no extra option needed

    /* Perform the request */
    res = curl_easy_perform(curl);

    /* Check for errors */
    if (res != CURLE_OK) {
        printf("CURL Request Failed: %s\n", curl_easy_strerror(res));
    } else {
        printf("API Request Successful: %s %s\n", request_method, url);
    }

    /* Cleanup */
    curl_easy_cleanup(curl);
    return (res == CURLE_OK) ? 0 : -1;
}