#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

#include "msys_clixon_http_customdevice.h"
#include "msys_sonic_device.h"


/*! Check if uri path denotes a customdevice path
 *
 * @param[in]  h      Clixon handle
 * @retval     1    Yes, a data path and "data" points to www-data if given
 * @retval     0    No, not a data path, or not enabled
 */
int
api_path_is_customdevice(clixon_handle h)
{
    int    retval = 0;
    char  *path = NULL;
    char  *http_data_path;

    /*
    if (restconf_http_data_get(h) == 1) //http data access permession for restconf
        goto done;
    this function can be implemented later for customdevice basically this is a config option <CLICON_FEATURE>clixon-restconf:http-data</CLICON_FEATURE>.
    */
    if ((path = restconf_uripath(h)) == NULL) /* extracts the URI path (/customdevice)*/
        goto done;
    
    /*
    <clixon-config>
        <CLICON_HTTP_DATA_PATH>/restconf/data</CLICON_HTTP_DATA_PATH>
    </clixon-config>
    clicon_option_str checks the CLICON_HTTP_DATA_PATH in the clixon.config file
    Adding an option to change the endpoint as per our requirement. Changing CLICON_HTTP_DATA_PATH with 
    */
    if ((http_data_path = clicon_option_str(h, "CUSTOM_DEVICE_HTTP_PATH")) == NULL)
        goto done;
    if (strlen(path) < strlen(http_data_path))
        goto done;
    if (path[0] != '/')
        goto done;

    /*Ensures that only the first part of path (up to the length of http_data_path) is compared.*/
    if (strncmp(path, http_data_path, strlen(http_data_path)) != 0) 
        goto done;
    retval = 1;
 done:
    
    if (path)
        free(path);
    return retval;
}


/*! Generic error function for custom device requests
 *
 * Handles multiple HTTP methods: GET, PUT, POST, PATCH, HEAD
 * Generates an appropriate error response with an HTML body.
 *
 * @param[in]  h      Clixon handle
 * @param[in]  req    Generic HTTP handle
 * @param[in]  code   HTTP error code (e.g., 400, 404, 500)
 * @retval     0      Success
 * @retval    -1      Error
 */
static int
api_http_customdevice_html_err(clixon_handle  h,
                          void          *req,
                          int            code)
{
    int   retval = -1;
    cbuf *cb = NULL;

    clixon_debug(CLIXON_DBG_RESTCONF, "");

    if ((cb = cbuf_new()) == NULL) {
        clixon_err(OE_UNIX, errno, "cbuf_new");
        goto done;
    }

    /* Set Content-Type header */
    if (restconf_reply_header(req, "Content-Type", "text/html") < 0)
        goto done;

    /* Generate an HTML response */
    cprintf(cb, "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\r\n");
    cprintf(cb, "<html><head>\r\n");
    cprintf(cb, "<title>%d %s</title>\r\n", code, restconf_code2reason(code));
    cprintf(cb, "</head><body>\r\n");
    cprintf(cb, "<h1>Error: %s</h1>\r\n", restconf_code2reason(code));
    cprintf(cb, "<p>Please check your request and try again.</p>\r\n");
    cprintf(cb, "</body></html>\r\n");

    /* Send the error response */
    if (restconf_reply_send(req, code, cb, 0) < 0)
        goto done;
    
    cb = NULL /* just incase if restconf_reply_send already used free on cb*/
    retval = 0;

done:
    if (cb)
        cbuf_free(cb);

    clixon_debug(CLIXON_DBG_RESTCONF, "");
    return retval;
}

/*! Generic error function for custom device requests (JSON response)
 *
 * Handles multiple HTTP methods: GET, PUT, POST, PATCH, HEAD
 * Generates an appropriate error response in JSON format.
 *
 * @param[in]  h      Clixon handle
 * @param[in]  req    Generic HTTP handle
 * @param[in]  code   HTTP error code (e.g., 400, 404, 500)
 * @retval     0      Success
 * @retval    -1      Error
 */
static int
api_http_customdevice_json_err(clixon_handle  h,
                               void          *req,
                               int            code)
{
    int   retval = -1;
    cbuf *cb = NULL;

    clixon_debug(CLIXON_DBG_RESTCONF, "");

    /* Allocate buffer for response */
    if ((cb = cbuf_new()) == NULL) {
        clixon_err(OE_UNIX, errno, "cbuf_new");
        goto done;
    }

    /* Set Content-Type header for JSON response */
    if (restconf_reply_header(req, "Content-Type", "application/yang-data+json") < 0)
        goto done;

    /* Generate a JSON error response */
    cprintf(cb, "{\n");
    cprintf(cb, "  \"ietf-restconf:errors\": {\n");
    cprintf(cb, "    \"error\": {\n");
    cprintf(cb, "      \"error-type\": \"rpc\",\n");
    cprintf(cb, "      \"error-tag\": \"%s\",\n", restconf_code2reason(code));
    cprintf(cb, "      \"error-severity\": \"error\",\n");
    cprintf(cb, "      \"error-message\": \"Request failed with HTTP code %d.\"\n", code);
    cprintf(cb, "    }\n");
    cprintf(cb, "  }\n");
    cprintf(cb, "}\n");

    /* Send the JSON error response */
    if (restconf_reply_send(req, code, cb, 0) < 0)
        goto done;

    cb = NULL; /* Prevents freeing after sending */
    retval = 0;

done:
    if (cb)
        cbuf_free(cb);

    clixon_debug(CLIXON_DBG_RESTCONF, "");
    return retval;
}

/*! Extract device name (between 2nd and 3rd '/') and device URL (from 3rd '/' onwards)
 *
 * @param[in]  uri         Full request URI (e.g., "/customdevice/sonicvs1/interfaces/interface")
 * @param[out] device_name Pointer to store the extracted device name (must be freed by caller)
 * @param[out] device_url  Pointer to store the extracted device URL (must be freed by caller)
 * @retval     0           Success
 * @retval     -1          Failure (invalid format)
 */
int extract_device_info(const char *uri, char **device_name, char **device_url) {
    int slash_count = 0;
    const char *start = NULL, *end = NULL, *url_start = NULL;

    if (!uri || !device_name || !device_url) {
        return -1;
    }

    /* Find the device name and device URL */
    for (const char *p = uri; *p; p++) {
        if (*p == '/') {
            slash_count++;
            if (slash_count == 2) {
                start = p + 1;  // Start of device name
            } else if (slash_count == 3) {
                end = p;        // End of device name
                url_start = p;  // Start of device URL
                break;
            }
        }
    }

    /* Check if we found required slashes */
    if (!start || !end || !url_start) {
        return -1;
    }

    /* Allocate and copy device name */
    size_t name_len = end - start;
    *device_name = (char *)malloc(name_len + 1);
    if (!*device_name) {
        return -1;
    }
    strncpy(*device_name, start, name_len);
    (*device_name)[name_len] = '\0';

    /* Allocate and copy device URL */
    *device_url = strdup(url_start);
    if (!*device_url) {
        free(*device_name);
        return -1;
    }

    return 0;
}

static int get_device_info(clixon_handle h, char **ip_address, char **device_type) {
    clixon_client_handle ch = NULL;

    /* Connect to Clixon using Netconf */
    if ((ch = clixon_client_connect(h, CLIXON_CLIENT_NETCONF, NULL)) == NULL)
        return -1;

    /* Allocate memory for ip_address */
    *ip_address = (char *)malloc(256);
    if (!*ip_address) {
        clixon_client_disconnect(ch);
        return -1;
    }

    /* Fetch the device's IP address */
    if (clixon_client_get_str(ch, *ip_address, 256, "http://project-technologies.com/device-inventory",
                              "/projectdevice:project-custom-devices/projectdevice:device[projectdevice:device-name='sonic1']/projectdevice:ip-address") < 0) {
        clixon_client_disconnect(ch);
        free(*ip_address);
        return -1;
    }

    /* Allocate memory for device_type */
    *device_type = (char *)malloc(256);
    if (!*device_type) {
        clixon_client_disconnect(ch);
        free(*ip_address);
        return -1;
    }

    /* Fetch the device type */
    if (clixon_client_get_str(ch, *device_type, 256, "http://project-technologies.com/device-inventory",
                              "/project-custom-devices/device[device-name='sonic1']/device-type") < 0) {
        clixon_client_disconnect(ch);
        free(*ip_address);
        free(*device_type);
        return -1;
    }

    clixon_client_disconnect(ch);
    return 0;
}

/*! operations for GET, PUT, POST etc customdevice request
 *
 * This implementation is constrained as follows:
 * 1. Enable as part of restconf and set URI in config file as CLICON_HTTP_DATA_PATH
 * 2. These function is entry point for the custom device reading from or writing to the configuration og the devices 
 * 3  operations: GET, PUT, POST, OPTIONS
 * 4. Decides which device to configure like (SONiC, Broadcom etc) based on how internally the device accepts the configuration request
 * 5. query parameters not supported
 * 6. Authentication as restconf
 * @param[in]  h         Clixon handle
 * @param[in]  req       Generic Www handle (can be part of clixon handle)
 * @param[in]  qvec      Query parameters, ie the ?<id>=<val>&<id>=<val> stuff
 * @retval     0    OK
 * @retval    -1    Error
 * Need to enable clixon-restconf.yang www-data feature
 */
int
api_http_customdevice(clixon_handle  h,
              void          *req,
              cvec          *qvec)
{
    int   retval = -1;
    char *request_method = NULL;
    int   head = 0;
    int   options = 0;
    cbuf *indata = NULL;
    char *path = NULL;
    int   ret;
    char *device_name = NULL;
    char *device_url = NULL;
    char *ip_address = NULL;
    char *device_type = NULL;

    clixon_debug(CLIXON_DBG_RESTCONF, "");
    if (req == NULL){
        errno = EINVAL;
        goto done;
    }
    /* 1. path: with stripped prefix, ultimately: dir/filename 
     */
    if (!api_path_is_customdevice(h)){
        if (api_http_customdevice_json_err(h, req, 404) < 0) /* not found */
            goto done;
        goto ok;
    }
    path = restconf_uripath(h);
    if ((path = restconf_param_get(h, "REQUEST_URI")) == NULL){
        clixon_err(OE_RESTCONF, 0, "No REQUEST_URI");
        return NULL;
    }
    /* 2. Get the device information */
    if (extract_device_info(path, &device_name, &device_url) != 0) {
        goto done;
    }
    request_method = restconf_param_get(h, "REQUEST_METHOD");
    /* send the information to the device and get ip and port if required*/
    if (get_device_info(h, &ip_address, &device_type) != 0) {
        if (api_http_customdevice_json_err(h, req, 404) < 0)  /* Not found */
            goto done;
        goto ok;
    }

    // Using if-else since switch-case doesn't support strings directly
    if (strcmp(device_type, "SONiC") == 0) {
        if (sonic_process_api(h ,req, qvec, device_url, ip_address, request_method) != 0)
            goto done
    } else if (strcmp(device_type, "Cisco") == 0) {
        printf("Handling Cisco device.\n");
    } else {
        printf("Handling other devices.\n");
    }

    // /*
    // if (strcmp(request_method, "GET") == 0){
    // }
    // else if (strcmp(request_method, "HEAD") == 0){
    //     head = 1;
    // }
    // else if (strcmp(request_method, "OPTIONS") == 0){
    //     options = 1;
    // }
    // else {
    //     if (api_http_data_err(h, req, 405) < 0) /* method not allowed */
    //     // goto done;
    //     // goto ok;
    // // }
    // */
    
    /* 3. query parameters not accepted */
    if (qvec != NULL){
        if (api_http_data_err(h, req, 400) < 0) /* bad request */
            goto done;
        goto ok;
    }
    /* 4. indata should be NULL (no write operations) */
    if ((indata = restconf_get_indata(req)) == NULL) {
        clixon_err(OE_RESTCONF, ENOENT, "Unexpected no input cbuf");
        goto done;
    }
    if (cbuf_len(indata)){
        if (api_http_data_err(h, req, 400) < 0) /* bad request */
            goto done;
        goto ok;
    }
    /* 6. Authenticate
     * Note, error handling may need change since it is restconf based
     */
    if ((ret = restconf_authentication_cb(h, req, 1, 0 /*media_out */)) < 0)
        goto done;
    if (ret == 0)
        goto ok;
    if (options){
        if (restconf_reply_header(req, "Allow", "OPTIONS,HEAD,GET") < 0)
            goto done;
        if (restconf_reply_send(req, 200, NULL, 0) < 0)
            goto done;
    }
    else if (api_http_data_file(h, req, path, head) < 0)
        goto done;
 ok:
    retval = 0;
 done:
    if (path)
        free(path);
    if (device_name)
        free(device_name);
        free(device_url);    
    clixon_debug(CLIXON_DBG_RESTCONF, "retval:%d", retval);
    return retval;
}
