#ifdef HAVE_CONFIG_H
#include "clixon_config.h" /* generated by config & autoconf */
#endif

/* clixon */
#include <clixon/clixon.h>


/*! Check if uri path denotes a data path
 *
 * @param[in]  h      Clixon handle
 * @retval     1    Yes, a data path and "data" points to www-data if given
 * @retval     0    No, not a data path, or not enabled
 */
int
api_path_is_customdevice(clixon_handle h)
{
    int    retval = 0;
    char  *path = NULL;
    char  *http_data_path;

    if (restconf_http_data_get(h) == 1) /*http data access permession for restconf*/
        goto done;
    if ((path = restconf_uripath(h)) == NULL)
        goto done;
    
    /*
    <clixon-config>
        <CLICON_HTTP_DATA_PATH>/restconf/data</CLICON_HTTP_DATA_PATH>
    </clixon-config>
    clicon_option_str checks the CLICON_HTTP_DATA_PATH in the clixon.config file
    */
    if ((http_data_path = clicon_option_str(h, "CLICON_HTTP_DATA_PATH")) == NULL)
        goto done;
    if (strlen(path) < strlen(http_data_path))
        goto done;
    if (path[0] != '/')
        goto done;
    if (strncmp(path, http_data_path, strlen(http_data_path)) != 0)
        goto done;
    retval = 1;
 done:
    if (path)
        free(path);
    return retval;
}